//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 01:43:49 PM CDT 
//


package mx.gob.sat.sitio_internet.cfd.catalogos.cartaporte;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_DerechosDePaso.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_DerechosDePaso"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;whiteSpace value="collapse"/&gt;
 *     &lt;enumeration value="CDP001"/&gt;
 *     &lt;enumeration value="CDP002"/&gt;
 *     &lt;enumeration value="CDP003"/&gt;
 *     &lt;enumeration value="CDP004"/&gt;
 *     &lt;enumeration value="CDP005"/&gt;
 *     &lt;enumeration value="CDP006"/&gt;
 *     &lt;enumeration value="CDP007"/&gt;
 *     &lt;enumeration value="CDP008"/&gt;
 *     &lt;enumeration value="CDP009"/&gt;
 *     &lt;enumeration value="CDP010"/&gt;
 *     &lt;enumeration value="CDP011"/&gt;
 *     &lt;enumeration value="CDP012"/&gt;
 *     &lt;enumeration value="CDP013"/&gt;
 *     &lt;enumeration value="CDP014"/&gt;
 *     &lt;enumeration value="CDP015"/&gt;
 *     &lt;enumeration value="CDP016"/&gt;
 *     &lt;enumeration value="CDP017"/&gt;
 *     &lt;enumeration value="CDP018"/&gt;
 *     &lt;enumeration value="CDP019"/&gt;
 *     &lt;enumeration value="CDP020"/&gt;
 *     &lt;enumeration value="CDP021"/&gt;
 *     &lt;enumeration value="CDP022"/&gt;
 *     &lt;enumeration value="CDP023"/&gt;
 *     &lt;enumeration value="CDP024"/&gt;
 *     &lt;enumeration value="CDP025"/&gt;
 *     &lt;enumeration value="CDP026"/&gt;
 *     &lt;enumeration value="CDP027"/&gt;
 *     &lt;enumeration value="CDP028"/&gt;
 *     &lt;enumeration value="CDP029"/&gt;
 *     &lt;enumeration value="CDP030"/&gt;
 *     &lt;enumeration value="CDP031"/&gt;
 *     &lt;enumeration value="CDP032"/&gt;
 *     &lt;enumeration value="CDP033"/&gt;
 *     &lt;enumeration value="CDP034"/&gt;
 *     &lt;enumeration value="CDP035"/&gt;
 *     &lt;enumeration value="CDP036"/&gt;
 *     &lt;enumeration value="CDP037"/&gt;
 *     &lt;enumeration value="CDP038"/&gt;
 *     &lt;enumeration value="CDP039"/&gt;
 *     &lt;enumeration value="CDP040"/&gt;
 *     &lt;enumeration value="CDP041"/&gt;
 *     &lt;enumeration value="CDP042"/&gt;
 *     &lt;enumeration value="CDP043"/&gt;
 *     &lt;enumeration value="CDP044"/&gt;
 *     &lt;enumeration value="CDP045"/&gt;
 *     &lt;enumeration value="CDP046"/&gt;
 *     &lt;enumeration value="CDP047"/&gt;
 *     &lt;enumeration value="CDP048"/&gt;
 *     &lt;enumeration value="CDP049"/&gt;
 *     &lt;enumeration value="CDP050"/&gt;
 *     &lt;enumeration value="CDP051"/&gt;
 *     &lt;enumeration value="CDP052"/&gt;
 *     &lt;enumeration value="CDP053"/&gt;
 *     &lt;enumeration value="CDP054"/&gt;
 *     &lt;enumeration value="CDP055"/&gt;
 *     &lt;enumeration value="CDP056"/&gt;
 *     &lt;enumeration value="CDP057"/&gt;
 *     &lt;enumeration value="CDP058"/&gt;
 *     &lt;enumeration value="CDP059"/&gt;
 *     &lt;enumeration value="CDP060"/&gt;
 *     &lt;enumeration value="CDP061"/&gt;
 *     &lt;enumeration value="CDP062"/&gt;
 *     &lt;enumeration value="CDP063"/&gt;
 *     &lt;enumeration value="CDP064"/&gt;
 *     &lt;enumeration value="CDP065"/&gt;
 *     &lt;enumeration value="CDP066"/&gt;
 *     &lt;enumeration value="CDP067"/&gt;
 *     &lt;enumeration value="CDP068"/&gt;
 *     &lt;enumeration value="CDP069"/&gt;
 *     &lt;enumeration value="CDP070"/&gt;
 *     &lt;enumeration value="CDP071"/&gt;
 *     &lt;enumeration value="CDP072"/&gt;
 *     &lt;enumeration value="CDP073"/&gt;
 *     &lt;enumeration value="CDP074"/&gt;
 *     &lt;enumeration value="CDP075"/&gt;
 *     &lt;enumeration value="CDP076"/&gt;
 *     &lt;enumeration value="CDP077"/&gt;
 *     &lt;enumeration value="CDP078"/&gt;
 *     &lt;enumeration value="CDP079"/&gt;
 *     &lt;enumeration value="CDP080"/&gt;
 *     &lt;enumeration value="CDP081"/&gt;
 *     &lt;enumeration value="CDP082"/&gt;
 *     &lt;enumeration value="CDP083"/&gt;
 *     &lt;enumeration value="CDP084"/&gt;
 *     &lt;enumeration value="CDP085"/&gt;
 *     &lt;enumeration value="CDP086"/&gt;
 *     &lt;enumeration value="CDP087"/&gt;
 *     &lt;enumeration value="CDP088"/&gt;
 *     &lt;enumeration value="CDP089"/&gt;
 *     &lt;enumeration value="CDP090"/&gt;
 *     &lt;enumeration value="CDP091"/&gt;
 *     &lt;enumeration value="CDP092"/&gt;
 *     &lt;enumeration value="CDP093"/&gt;
 *     &lt;enumeration value="CDP094"/&gt;
 *     &lt;enumeration value="CDP095"/&gt;
 *     &lt;enumeration value="CDP096"/&gt;
 *     &lt;enumeration value="CDP097"/&gt;
 *     &lt;enumeration value="CDP098"/&gt;
 *     &lt;enumeration value="CDP099"/&gt;
 *     &lt;enumeration value="CDP100"/&gt;
 *     &lt;enumeration value="CDP101"/&gt;
 *     &lt;enumeration value="CDP102"/&gt;
 *     &lt;enumeration value="CDP103"/&gt;
 *     &lt;enumeration value="CDP104"/&gt;
 *     &lt;enumeration value="CDP105"/&gt;
 *     &lt;enumeration value="CDP106"/&gt;
 *     &lt;enumeration value="CDP107"/&gt;
 *     &lt;enumeration value="CDP108"/&gt;
 *     &lt;enumeration value="CDP109"/&gt;
 *     &lt;enumeration value="CDP110"/&gt;
 *     &lt;enumeration value="CDP111"/&gt;
 *     &lt;enumeration value="CDP112"/&gt;
 *     &lt;enumeration value="CDP113"/&gt;
 *     &lt;enumeration value="CDP114"/&gt;
 *     &lt;enumeration value="CDP115"/&gt;
 *     &lt;enumeration value="CDP116"/&gt;
 *     &lt;enumeration value="CDP117"/&gt;
 *     &lt;enumeration value="CDP118"/&gt;
 *     &lt;enumeration value="CDP119"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "c_DerechosDePaso", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte")
@XmlEnum
public enum CDerechosDePaso {

    @XmlEnumValue("CDP001")
    CDP_001("CDP001"),
    @XmlEnumValue("CDP002")
    CDP_002("CDP002"),
    @XmlEnumValue("CDP003")
    CDP_003("CDP003"),
    @XmlEnumValue("CDP004")
    CDP_004("CDP004"),
    @XmlEnumValue("CDP005")
    CDP_005("CDP005"),
    @XmlEnumValue("CDP006")
    CDP_006("CDP006"),
    @XmlEnumValue("CDP007")
    CDP_007("CDP007"),
    @XmlEnumValue("CDP008")
    CDP_008("CDP008"),
    @XmlEnumValue("CDP009")
    CDP_009("CDP009"),
    @XmlEnumValue("CDP010")
    CDP_010("CDP010"),
    @XmlEnumValue("CDP011")
    CDP_011("CDP011"),
    @XmlEnumValue("CDP012")
    CDP_012("CDP012"),
    @XmlEnumValue("CDP013")
    CDP_013("CDP013"),
    @XmlEnumValue("CDP014")
    CDP_014("CDP014"),
    @XmlEnumValue("CDP015")
    CDP_015("CDP015"),
    @XmlEnumValue("CDP016")
    CDP_016("CDP016"),
    @XmlEnumValue("CDP017")
    CDP_017("CDP017"),
    @XmlEnumValue("CDP018")
    CDP_018("CDP018"),
    @XmlEnumValue("CDP019")
    CDP_019("CDP019"),
    @XmlEnumValue("CDP020")
    CDP_020("CDP020"),
    @XmlEnumValue("CDP021")
    CDP_021("CDP021"),
    @XmlEnumValue("CDP022")
    CDP_022("CDP022"),
    @XmlEnumValue("CDP023")
    CDP_023("CDP023"),
    @XmlEnumValue("CDP024")
    CDP_024("CDP024"),
    @XmlEnumValue("CDP025")
    CDP_025("CDP025"),
    @XmlEnumValue("CDP026")
    CDP_026("CDP026"),
    @XmlEnumValue("CDP027")
    CDP_027("CDP027"),
    @XmlEnumValue("CDP028")
    CDP_028("CDP028"),
    @XmlEnumValue("CDP029")
    CDP_029("CDP029"),
    @XmlEnumValue("CDP030")
    CDP_030("CDP030"),
    @XmlEnumValue("CDP031")
    CDP_031("CDP031"),
    @XmlEnumValue("CDP032")
    CDP_032("CDP032"),
    @XmlEnumValue("CDP033")
    CDP_033("CDP033"),
    @XmlEnumValue("CDP034")
    CDP_034("CDP034"),
    @XmlEnumValue("CDP035")
    CDP_035("CDP035"),
    @XmlEnumValue("CDP036")
    CDP_036("CDP036"),
    @XmlEnumValue("CDP037")
    CDP_037("CDP037"),
    @XmlEnumValue("CDP038")
    CDP_038("CDP038"),
    @XmlEnumValue("CDP039")
    CDP_039("CDP039"),
    @XmlEnumValue("CDP040")
    CDP_040("CDP040"),
    @XmlEnumValue("CDP041")
    CDP_041("CDP041"),
    @XmlEnumValue("CDP042")
    CDP_042("CDP042"),
    @XmlEnumValue("CDP043")
    CDP_043("CDP043"),
    @XmlEnumValue("CDP044")
    CDP_044("CDP044"),
    @XmlEnumValue("CDP045")
    CDP_045("CDP045"),
    @XmlEnumValue("CDP046")
    CDP_046("CDP046"),
    @XmlEnumValue("CDP047")
    CDP_047("CDP047"),
    @XmlEnumValue("CDP048")
    CDP_048("CDP048"),
    @XmlEnumValue("CDP049")
    CDP_049("CDP049"),
    @XmlEnumValue("CDP050")
    CDP_050("CDP050"),
    @XmlEnumValue("CDP051")
    CDP_051("CDP051"),
    @XmlEnumValue("CDP052")
    CDP_052("CDP052"),
    @XmlEnumValue("CDP053")
    CDP_053("CDP053"),
    @XmlEnumValue("CDP054")
    CDP_054("CDP054"),
    @XmlEnumValue("CDP055")
    CDP_055("CDP055"),
    @XmlEnumValue("CDP056")
    CDP_056("CDP056"),
    @XmlEnumValue("CDP057")
    CDP_057("CDP057"),
    @XmlEnumValue("CDP058")
    CDP_058("CDP058"),
    @XmlEnumValue("CDP059")
    CDP_059("CDP059"),
    @XmlEnumValue("CDP060")
    CDP_060("CDP060"),
    @XmlEnumValue("CDP061")
    CDP_061("CDP061"),
    @XmlEnumValue("CDP062")
    CDP_062("CDP062"),
    @XmlEnumValue("CDP063")
    CDP_063("CDP063"),
    @XmlEnumValue("CDP064")
    CDP_064("CDP064"),
    @XmlEnumValue("CDP065")
    CDP_065("CDP065"),
    @XmlEnumValue("CDP066")
    CDP_066("CDP066"),
    @XmlEnumValue("CDP067")
    CDP_067("CDP067"),
    @XmlEnumValue("CDP068")
    CDP_068("CDP068"),
    @XmlEnumValue("CDP069")
    CDP_069("CDP069"),
    @XmlEnumValue("CDP070")
    CDP_070("CDP070"),
    @XmlEnumValue("CDP071")
    CDP_071("CDP071"),
    @XmlEnumValue("CDP072")
    CDP_072("CDP072"),
    @XmlEnumValue("CDP073")
    CDP_073("CDP073"),
    @XmlEnumValue("CDP074")
    CDP_074("CDP074"),
    @XmlEnumValue("CDP075")
    CDP_075("CDP075"),
    @XmlEnumValue("CDP076")
    CDP_076("CDP076"),
    @XmlEnumValue("CDP077")
    CDP_077("CDP077"),
    @XmlEnumValue("CDP078")
    CDP_078("CDP078"),
    @XmlEnumValue("CDP079")
    CDP_079("CDP079"),
    @XmlEnumValue("CDP080")
    CDP_080("CDP080"),
    @XmlEnumValue("CDP081")
    CDP_081("CDP081"),
    @XmlEnumValue("CDP082")
    CDP_082("CDP082"),
    @XmlEnumValue("CDP083")
    CDP_083("CDP083"),
    @XmlEnumValue("CDP084")
    CDP_084("CDP084"),
    @XmlEnumValue("CDP085")
    CDP_085("CDP085"),
    @XmlEnumValue("CDP086")
    CDP_086("CDP086"),
    @XmlEnumValue("CDP087")
    CDP_087("CDP087"),
    @XmlEnumValue("CDP088")
    CDP_088("CDP088"),
    @XmlEnumValue("CDP089")
    CDP_089("CDP089"),
    @XmlEnumValue("CDP090")
    CDP_090("CDP090"),
    @XmlEnumValue("CDP091")
    CDP_091("CDP091"),
    @XmlEnumValue("CDP092")
    CDP_092("CDP092"),
    @XmlEnumValue("CDP093")
    CDP_093("CDP093"),
    @XmlEnumValue("CDP094")
    CDP_094("CDP094"),
    @XmlEnumValue("CDP095")
    CDP_095("CDP095"),
    @XmlEnumValue("CDP096")
    CDP_096("CDP096"),
    @XmlEnumValue("CDP097")
    CDP_097("CDP097"),
    @XmlEnumValue("CDP098")
    CDP_098("CDP098"),
    @XmlEnumValue("CDP099")
    CDP_099("CDP099"),
    @XmlEnumValue("CDP100")
    CDP_100("CDP100"),
    @XmlEnumValue("CDP101")
    CDP_101("CDP101"),
    @XmlEnumValue("CDP102")
    CDP_102("CDP102"),
    @XmlEnumValue("CDP103")
    CDP_103("CDP103"),
    @XmlEnumValue("CDP104")
    CDP_104("CDP104"),
    @XmlEnumValue("CDP105")
    CDP_105("CDP105"),
    @XmlEnumValue("CDP106")
    CDP_106("CDP106"),
    @XmlEnumValue("CDP107")
    CDP_107("CDP107"),
    @XmlEnumValue("CDP108")
    CDP_108("CDP108"),
    @XmlEnumValue("CDP109")
    CDP_109("CDP109"),
    @XmlEnumValue("CDP110")
    CDP_110("CDP110"),
    @XmlEnumValue("CDP111")
    CDP_111("CDP111"),
    @XmlEnumValue("CDP112")
    CDP_112("CDP112"),
    @XmlEnumValue("CDP113")
    CDP_113("CDP113"),
    @XmlEnumValue("CDP114")
    CDP_114("CDP114"),
    @XmlEnumValue("CDP115")
    CDP_115("CDP115"),
    @XmlEnumValue("CDP116")
    CDP_116("CDP116"),
    @XmlEnumValue("CDP117")
    CDP_117("CDP117"),
    @XmlEnumValue("CDP118")
    CDP_118("CDP118"),
    @XmlEnumValue("CDP119")
    CDP_119("CDP119");
    private final String value;

    CDerechosDePaso(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CDerechosDePaso fromValue(String v) {
        for (CDerechosDePaso c: CDerechosDePaso.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
