//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 01:43:49 PM CDT 
//


package mx.gob.sat.sitio_internet.cfd.catalogos.cartaporte;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_NumAutorizacionNaviero.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_NumAutorizacionNaviero"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;whiteSpace value="collapse"/&gt;
 *     &lt;enumeration value="SCT418/020/2016"/&gt;
 *     &lt;enumeration value="SCT418/021/2016"/&gt;
 *     &lt;enumeration value="SCT418/025/2016"/&gt;
 *     &lt;enumeration value="SCT418/026/2016"/&gt;
 *     &lt;enumeration value="SCT418/028/2016"/&gt;
 *     &lt;enumeration value="SCT418/029/2016"/&gt;
 *     &lt;enumeration value="SCT418/030/2016"/&gt;
 *     &lt;enumeration value="SCT418/034/2016"/&gt;
 *     &lt;enumeration value="SCT418/036/2016"/&gt;
 *     &lt;enumeration value="SCT418/042/2016"/&gt;
 *     &lt;enumeration value="SCT418/046/2016"/&gt;
 *     &lt;enumeration value="SCT418/047/2016"/&gt;
 *     &lt;enumeration value="SCT418/048/2016"/&gt;
 *     &lt;enumeration value="SCT418/051/2016"/&gt;
 *     &lt;enumeration value="SCT418/052/2016"/&gt;
 *     &lt;enumeration value="SCT418/010/2017"/&gt;
 *     &lt;enumeration value="SCT418/014/2017"/&gt;
 *     &lt;enumeration value="SCT418/017/2017"/&gt;
 *     &lt;enumeration value="SCT418/021/2017"/&gt;
 *     &lt;enumeration value="SCT418/022/2017"/&gt;
 *     &lt;enumeration value="SCT418/023/2017"/&gt;
 *     &lt;enumeration value="SCT418/024/2017"/&gt;
 *     &lt;enumeration value="SCT418/030/2017"/&gt;
 *     &lt;enumeration value="SCT418/031/2017"/&gt;
 *     &lt;enumeration value="SCT418/034/2017"/&gt;
 *     &lt;enumeration value="SCT418/035/2017"/&gt;
 *     &lt;enumeration value="SCT418/038/2017"/&gt;
 *     &lt;enumeration value="SCT418/044/2017"/&gt;
 *     &lt;enumeration value="SCT418/045/2017"/&gt;
 *     &lt;enumeration value="SCT418/047/2017"/&gt;
 *     &lt;enumeration value="SCT418/053/2017"/&gt;
 *     &lt;enumeration value="SCT418/054/2017"/&gt;
 *     &lt;enumeration value="SCT418/056/2017"/&gt;
 *     &lt;enumeration value="SCT418/057/2017"/&gt;
 *     &lt;enumeration value="SCT418/060/2017"/&gt;
 *     &lt;enumeration value="SCT418/061/2017"/&gt;
 *     &lt;enumeration value="SCT418/064/2017"/&gt;
 *     &lt;enumeration value="SCT418/065/2017"/&gt;
 *     &lt;enumeration value="SCT418/006/2018"/&gt;
 *     &lt;enumeration value="SCT418/013/2018"/&gt;
 *     &lt;enumeration value="SCT418/014/2018"/&gt;
 *     &lt;enumeration value="SCT418/017/2018"/&gt;
 *     &lt;enumeration value="SCT418/018/2018"/&gt;
 *     &lt;enumeration value="SCT418/019/2018"/&gt;
 *     &lt;enumeration value="SCT418/022/2018"/&gt;
 *     &lt;enumeration value="SCT418/026/2018"/&gt;
 *     &lt;enumeration value="SCT418/031/2018"/&gt;
 *     &lt;enumeration value="SCT418/033/2018"/&gt;
 *     &lt;enumeration value="SCT418/037/2018"/&gt;
 *     &lt;enumeration value="SCT418/038/2018"/&gt;
 *     &lt;enumeration value="SCT418/040/2018"/&gt;
 *     &lt;enumeration value="SCT418/041/2018"/&gt;
 *     &lt;enumeration value="SCT418/043/2018"/&gt;
 *     &lt;enumeration value="SCT418/045/2018"/&gt;
 *     &lt;enumeration value="SCT418/046/2018"/&gt;
 *     &lt;enumeration value="SCT418/048/2018"/&gt;
 *     &lt;enumeration value="SCT418/050/2018"/&gt;
 *     &lt;enumeration value="SCT418/053/2018"/&gt;
 *     &lt;enumeration value="SCT418/057/2018"/&gt;
 *     &lt;enumeration value="SCT418/068/2018"/&gt;
 *     &lt;enumeration value="SCT418/003/2019"/&gt;
 *     &lt;enumeration value="SCT418/005/2019"/&gt;
 *     &lt;enumeration value="SCT418/013/2019"/&gt;
 *     &lt;enumeration value="SCT418/015/2019"/&gt;
 *     &lt;enumeration value="SCT418/020/2019"/&gt;
 *     &lt;enumeration value="SCT418/025/2019"/&gt;
 *     &lt;enumeration value="SCT418/026/2019"/&gt;
 *     &lt;enumeration value="SCT418/027/2019"/&gt;
 *     &lt;enumeration value="SCT418/029/2019"/&gt;
 *     &lt;enumeration value="SCT418/036/2019"/&gt;
 *     &lt;enumeration value="SCT418/037/2019"/&gt;
 *     &lt;enumeration value="SCT418/038/2019"/&gt;
 *     &lt;enumeration value="SCT418/041/2019"/&gt;
 *     &lt;enumeration value="SCT418/045/2019"/&gt;
 *     &lt;enumeration value="SCT418/046/2019"/&gt;
 *     &lt;enumeration value="SCT418/003/2020"/&gt;
 *     &lt;enumeration value="SCT418/005/2020"/&gt;
 *     &lt;enumeration value="SCT418/006/2020"/&gt;
 *     &lt;enumeration value="SCT418/010/2020"/&gt;
 *     &lt;enumeration value="SCT418/011/2020"/&gt;
 *     &lt;enumeration value="SCT418/012/2020"/&gt;
 *     &lt;enumeration value="SCT418/013/2020"/&gt;
 *     &lt;enumeration value="SCT418/023/2020"/&gt;
 *     &lt;enumeration value="SCT418/024/2020"/&gt;
 *     &lt;enumeration value="SCT418/025/2020"/&gt;
 *     &lt;enumeration value="SCT418/026/2020"/&gt;
 *     &lt;enumeration value="SCT418/027/2020"/&gt;
 *     &lt;enumeration value="SCT418/029/2020"/&gt;
 *     &lt;enumeration value="SCT418/030/2020"/&gt;
 *     &lt;enumeration value="SCT418/031/2020"/&gt;
 *     &lt;enumeration value="SCT418/032/2020"/&gt;
 *     &lt;enumeration value="SCT418/033/2020"/&gt;
 *     &lt;enumeration value="SCT418/035/2020"/&gt;
 *     &lt;enumeration value="SCT418/036/2020"/&gt;
 *     &lt;enumeration value="SCT418/037/2020"/&gt;
 *     &lt;enumeration value="SCT418/040/2020"/&gt;
 *     &lt;enumeration value="SCT418/041/2020"/&gt;
 *     &lt;enumeration value="SCT418/042/2020"/&gt;
 *     &lt;enumeration value="SCT418/001/2021"/&gt;
 *     &lt;enumeration value="SCT418/005/2021"/&gt;
 *     &lt;enumeration value="SCT418/006/2021"/&gt;
 *     &lt;enumeration value="SCT418/007/2021"/&gt;
 *     &lt;enumeration value="SCT418/013/2021"/&gt;
 *     &lt;enumeration value="SCT418/020/2021"/&gt;
 *     &lt;enumeration value="SCT418/021/2021"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "c_NumAutorizacionNaviero", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte")
@XmlEnum
public enum CNumAutorizacionNaviero {

    @XmlEnumValue("SCT418/020/2016")
    SCT_418_020_2016("SCT418/020/2016"),
    @XmlEnumValue("SCT418/021/2016")
    SCT_418_021_2016("SCT418/021/2016"),
    @XmlEnumValue("SCT418/025/2016")
    SCT_418_025_2016("SCT418/025/2016"),
    @XmlEnumValue("SCT418/026/2016")
    SCT_418_026_2016("SCT418/026/2016"),
    @XmlEnumValue("SCT418/028/2016")
    SCT_418_028_2016("SCT418/028/2016"),
    @XmlEnumValue("SCT418/029/2016")
    SCT_418_029_2016("SCT418/029/2016"),
    @XmlEnumValue("SCT418/030/2016")
    SCT_418_030_2016("SCT418/030/2016"),
    @XmlEnumValue("SCT418/034/2016")
    SCT_418_034_2016("SCT418/034/2016"),
    @XmlEnumValue("SCT418/036/2016")
    SCT_418_036_2016("SCT418/036/2016"),
    @XmlEnumValue("SCT418/042/2016")
    SCT_418_042_2016("SCT418/042/2016"),
    @XmlEnumValue("SCT418/046/2016")
    SCT_418_046_2016("SCT418/046/2016"),
    @XmlEnumValue("SCT418/047/2016")
    SCT_418_047_2016("SCT418/047/2016"),
    @XmlEnumValue("SCT418/048/2016")
    SCT_418_048_2016("SCT418/048/2016"),
    @XmlEnumValue("SCT418/051/2016")
    SCT_418_051_2016("SCT418/051/2016"),
    @XmlEnumValue("SCT418/052/2016")
    SCT_418_052_2016("SCT418/052/2016"),
    @XmlEnumValue("SCT418/010/2017")
    SCT_418_010_2017("SCT418/010/2017"),
    @XmlEnumValue("SCT418/014/2017")
    SCT_418_014_2017("SCT418/014/2017"),
    @XmlEnumValue("SCT418/017/2017")
    SCT_418_017_2017("SCT418/017/2017"),
    @XmlEnumValue("SCT418/021/2017")
    SCT_418_021_2017("SCT418/021/2017"),
    @XmlEnumValue("SCT418/022/2017")
    SCT_418_022_2017("SCT418/022/2017"),
    @XmlEnumValue("SCT418/023/2017")
    SCT_418_023_2017("SCT418/023/2017"),
    @XmlEnumValue("SCT418/024/2017")
    SCT_418_024_2017("SCT418/024/2017"),
    @XmlEnumValue("SCT418/030/2017")
    SCT_418_030_2017("SCT418/030/2017"),
    @XmlEnumValue("SCT418/031/2017")
    SCT_418_031_2017("SCT418/031/2017"),
    @XmlEnumValue("SCT418/034/2017")
    SCT_418_034_2017("SCT418/034/2017"),
    @XmlEnumValue("SCT418/035/2017")
    SCT_418_035_2017("SCT418/035/2017"),
    @XmlEnumValue("SCT418/038/2017")
    SCT_418_038_2017("SCT418/038/2017"),
    @XmlEnumValue("SCT418/044/2017")
    SCT_418_044_2017("SCT418/044/2017"),
    @XmlEnumValue("SCT418/045/2017")
    SCT_418_045_2017("SCT418/045/2017"),
    @XmlEnumValue("SCT418/047/2017")
    SCT_418_047_2017("SCT418/047/2017"),
    @XmlEnumValue("SCT418/053/2017")
    SCT_418_053_2017("SCT418/053/2017"),
    @XmlEnumValue("SCT418/054/2017")
    SCT_418_054_2017("SCT418/054/2017"),
    @XmlEnumValue("SCT418/056/2017")
    SCT_418_056_2017("SCT418/056/2017"),
    @XmlEnumValue("SCT418/057/2017")
    SCT_418_057_2017("SCT418/057/2017"),
    @XmlEnumValue("SCT418/060/2017")
    SCT_418_060_2017("SCT418/060/2017"),
    @XmlEnumValue("SCT418/061/2017")
    SCT_418_061_2017("SCT418/061/2017"),
    @XmlEnumValue("SCT418/064/2017")
    SCT_418_064_2017("SCT418/064/2017"),
    @XmlEnumValue("SCT418/065/2017")
    SCT_418_065_2017("SCT418/065/2017"),
    @XmlEnumValue("SCT418/006/2018")
    SCT_418_006_2018("SCT418/006/2018"),
    @XmlEnumValue("SCT418/013/2018")
    SCT_418_013_2018("SCT418/013/2018"),
    @XmlEnumValue("SCT418/014/2018")
    SCT_418_014_2018("SCT418/014/2018"),
    @XmlEnumValue("SCT418/017/2018")
    SCT_418_017_2018("SCT418/017/2018"),
    @XmlEnumValue("SCT418/018/2018")
    SCT_418_018_2018("SCT418/018/2018"),
    @XmlEnumValue("SCT418/019/2018")
    SCT_418_019_2018("SCT418/019/2018"),
    @XmlEnumValue("SCT418/022/2018")
    SCT_418_022_2018("SCT418/022/2018"),
    @XmlEnumValue("SCT418/026/2018")
    SCT_418_026_2018("SCT418/026/2018"),
    @XmlEnumValue("SCT418/031/2018")
    SCT_418_031_2018("SCT418/031/2018"),
    @XmlEnumValue("SCT418/033/2018")
    SCT_418_033_2018("SCT418/033/2018"),
    @XmlEnumValue("SCT418/037/2018")
    SCT_418_037_2018("SCT418/037/2018"),
    @XmlEnumValue("SCT418/038/2018")
    SCT_418_038_2018("SCT418/038/2018"),
    @XmlEnumValue("SCT418/040/2018")
    SCT_418_040_2018("SCT418/040/2018"),
    @XmlEnumValue("SCT418/041/2018")
    SCT_418_041_2018("SCT418/041/2018"),
    @XmlEnumValue("SCT418/043/2018")
    SCT_418_043_2018("SCT418/043/2018"),
    @XmlEnumValue("SCT418/045/2018")
    SCT_418_045_2018("SCT418/045/2018"),
    @XmlEnumValue("SCT418/046/2018")
    SCT_418_046_2018("SCT418/046/2018"),
    @XmlEnumValue("SCT418/048/2018")
    SCT_418_048_2018("SCT418/048/2018"),
    @XmlEnumValue("SCT418/050/2018")
    SCT_418_050_2018("SCT418/050/2018"),
    @XmlEnumValue("SCT418/053/2018")
    SCT_418_053_2018("SCT418/053/2018"),
    @XmlEnumValue("SCT418/057/2018")
    SCT_418_057_2018("SCT418/057/2018"),
    @XmlEnumValue("SCT418/068/2018")
    SCT_418_068_2018("SCT418/068/2018"),
    @XmlEnumValue("SCT418/003/2019")
    SCT_418_003_2019("SCT418/003/2019"),
    @XmlEnumValue("SCT418/005/2019")
    SCT_418_005_2019("SCT418/005/2019"),
    @XmlEnumValue("SCT418/013/2019")
    SCT_418_013_2019("SCT418/013/2019"),
    @XmlEnumValue("SCT418/015/2019")
    SCT_418_015_2019("SCT418/015/2019"),
    @XmlEnumValue("SCT418/020/2019")
    SCT_418_020_2019("SCT418/020/2019"),
    @XmlEnumValue("SCT418/025/2019")
    SCT_418_025_2019("SCT418/025/2019"),
    @XmlEnumValue("SCT418/026/2019")
    SCT_418_026_2019("SCT418/026/2019"),
    @XmlEnumValue("SCT418/027/2019")
    SCT_418_027_2019("SCT418/027/2019"),
    @XmlEnumValue("SCT418/029/2019")
    SCT_418_029_2019("SCT418/029/2019"),
    @XmlEnumValue("SCT418/036/2019")
    SCT_418_036_2019("SCT418/036/2019"),
    @XmlEnumValue("SCT418/037/2019")
    SCT_418_037_2019("SCT418/037/2019"),
    @XmlEnumValue("SCT418/038/2019")
    SCT_418_038_2019("SCT418/038/2019"),
    @XmlEnumValue("SCT418/041/2019")
    SCT_418_041_2019("SCT418/041/2019"),
    @XmlEnumValue("SCT418/045/2019")
    SCT_418_045_2019("SCT418/045/2019"),
    @XmlEnumValue("SCT418/046/2019")
    SCT_418_046_2019("SCT418/046/2019"),
    @XmlEnumValue("SCT418/003/2020")
    SCT_418_003_2020("SCT418/003/2020"),
    @XmlEnumValue("SCT418/005/2020")
    SCT_418_005_2020("SCT418/005/2020"),
    @XmlEnumValue("SCT418/006/2020")
    SCT_418_006_2020("SCT418/006/2020"),
    @XmlEnumValue("SCT418/010/2020")
    SCT_418_010_2020("SCT418/010/2020"),
    @XmlEnumValue("SCT418/011/2020")
    SCT_418_011_2020("SCT418/011/2020"),
    @XmlEnumValue("SCT418/012/2020")
    SCT_418_012_2020("SCT418/012/2020"),
    @XmlEnumValue("SCT418/013/2020")
    SCT_418_013_2020("SCT418/013/2020"),
    @XmlEnumValue("SCT418/023/2020")
    SCT_418_023_2020("SCT418/023/2020"),
    @XmlEnumValue("SCT418/024/2020")
    SCT_418_024_2020("SCT418/024/2020"),
    @XmlEnumValue("SCT418/025/2020")
    SCT_418_025_2020("SCT418/025/2020"),
    @XmlEnumValue("SCT418/026/2020")
    SCT_418_026_2020("SCT418/026/2020"),
    @XmlEnumValue("SCT418/027/2020")
    SCT_418_027_2020("SCT418/027/2020"),
    @XmlEnumValue("SCT418/029/2020")
    SCT_418_029_2020("SCT418/029/2020"),
    @XmlEnumValue("SCT418/030/2020")
    SCT_418_030_2020("SCT418/030/2020"),
    @XmlEnumValue("SCT418/031/2020")
    SCT_418_031_2020("SCT418/031/2020"),
    @XmlEnumValue("SCT418/032/2020")
    SCT_418_032_2020("SCT418/032/2020"),
    @XmlEnumValue("SCT418/033/2020")
    SCT_418_033_2020("SCT418/033/2020"),
    @XmlEnumValue("SCT418/035/2020")
    SCT_418_035_2020("SCT418/035/2020"),
    @XmlEnumValue("SCT418/036/2020")
    SCT_418_036_2020("SCT418/036/2020"),
    @XmlEnumValue("SCT418/037/2020")
    SCT_418_037_2020("SCT418/037/2020"),
    @XmlEnumValue("SCT418/040/2020")
    SCT_418_040_2020("SCT418/040/2020"),
    @XmlEnumValue("SCT418/041/2020")
    SCT_418_041_2020("SCT418/041/2020"),
    @XmlEnumValue("SCT418/042/2020")
    SCT_418_042_2020("SCT418/042/2020"),
    @XmlEnumValue("SCT418/001/2021")
    SCT_418_001_2021("SCT418/001/2021"),
    @XmlEnumValue("SCT418/005/2021")
    SCT_418_005_2021("SCT418/005/2021"),
    @XmlEnumValue("SCT418/006/2021")
    SCT_418_006_2021("SCT418/006/2021"),
    @XmlEnumValue("SCT418/007/2021")
    SCT_418_007_2021("SCT418/007/2021"),
    @XmlEnumValue("SCT418/013/2021")
    SCT_418_013_2021("SCT418/013/2021"),
    @XmlEnumValue("SCT418/020/2021")
    SCT_418_020_2021("SCT418/020/2021"),
    @XmlEnumValue("SCT418/021/2021")
    SCT_418_021_2021("SCT418/021/2021");
    private final String value;

    CNumAutorizacionNaviero(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CNumAutorizacionNaviero fromValue(String v) {
        for (CNumAutorizacionNaviero c: CNumAutorizacionNaviero.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
