//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 01:43:49 PM CDT 
//


package mx.gob.sat.sitio_internet.cfd.catalogos.cartaporte;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_TipoDeServicio.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_TipoDeServicio"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;whiteSpace value="collapse"/&gt;
 *     &lt;enumeration value="TS01"/&gt;
 *     &lt;enumeration value="TS02"/&gt;
 *     &lt;enumeration value="TS03"/&gt;
 *     &lt;enumeration value="TS04"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "c_TipoDeServicio", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte")
@XmlEnum
public enum CTipoDeServicio {

    @XmlEnumValue("TS01")
    TS_01("TS01"),
    @XmlEnumValue("TS02")
    TS_02("TS02"),
    @XmlEnumValue("TS03")
    TS_03("TS03"),
    @XmlEnumValue("TS04")
    TS_04("TS04");
    private final String value;

    CTipoDeServicio(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CTipoDeServicio fromValue(String v) {
        for (CTipoDeServicio c: CTipoDeServicio.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
