//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.02 at 05:28:47 PM CST 
//


package mx.gob.sat.sitio_internet.cfd.catalogos.cartaporte;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_ClaveTipoCarga.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_ClaveTipoCarga">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="CGS"/>
 *     &lt;enumeration value="CGC"/>
 *     &lt;enumeration value="GMN"/>
 *     &lt;enumeration value="GAG"/>
 *     &lt;enumeration value="OFL"/>
 *     &lt;enumeration value="PYD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "c_ClaveTipoCarga", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte")
@XmlEnum
public enum CClaveTipoCarga {

    CGS,
    CGC,
    GMN,
    GAG,
    OFL,
    PYD;

    public String value() {
        return name();
    }

    public static CClaveTipoCarga fromValue(String v) {
        return valueOf(v);
    }

}
