//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.02 at 05:28:47 PM CST 
//


package mx.gob.sat.sitio_internet.cfd.catalogos.cartaporte;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_CodigoTransporteAereo.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_CodigoTransporteAereo">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="CA001"/>
 *     &lt;enumeration value="CA002"/>
 *     &lt;enumeration value="CA003"/>
 *     &lt;enumeration value="CA004"/>
 *     &lt;enumeration value="CA005"/>
 *     &lt;enumeration value="CA006"/>
 *     &lt;enumeration value="CA007"/>
 *     &lt;enumeration value="CA008"/>
 *     &lt;enumeration value="CA009"/>
 *     &lt;enumeration value="CA010"/>
 *     &lt;enumeration value="CA011"/>
 *     &lt;enumeration value="CA012"/>
 *     &lt;enumeration value="CA013"/>
 *     &lt;enumeration value="CA014"/>
 *     &lt;enumeration value="CA015"/>
 *     &lt;enumeration value="CA016"/>
 *     &lt;enumeration value="CA017"/>
 *     &lt;enumeration value="CA018"/>
 *     &lt;enumeration value="CA019"/>
 *     &lt;enumeration value="CA020"/>
 *     &lt;enumeration value="CA021"/>
 *     &lt;enumeration value="CA022"/>
 *     &lt;enumeration value="CA023"/>
 *     &lt;enumeration value="CA024"/>
 *     &lt;enumeration value="CA025"/>
 *     &lt;enumeration value="CA026"/>
 *     &lt;enumeration value="CA027"/>
 *     &lt;enumeration value="CA028"/>
 *     &lt;enumeration value="CA029"/>
 *     &lt;enumeration value="CA030"/>
 *     &lt;enumeration value="CA031"/>
 *     &lt;enumeration value="CA032"/>
 *     &lt;enumeration value="CA033"/>
 *     &lt;enumeration value="CA034"/>
 *     &lt;enumeration value="CA035"/>
 *     &lt;enumeration value="CA036"/>
 *     &lt;enumeration value="CA037"/>
 *     &lt;enumeration value="CA038"/>
 *     &lt;enumeration value="CA039"/>
 *     &lt;enumeration value="CA040"/>
 *     &lt;enumeration value="CA041"/>
 *     &lt;enumeration value="CA042"/>
 *     &lt;enumeration value="CA043"/>
 *     &lt;enumeration value="CA044"/>
 *     &lt;enumeration value="CA045"/>
 *     &lt;enumeration value="CA046"/>
 *     &lt;enumeration value="CA047"/>
 *     &lt;enumeration value="CA048"/>
 *     &lt;enumeration value="CA049"/>
 *     &lt;enumeration value="CA050"/>
 *     &lt;enumeration value="CA051"/>
 *     &lt;enumeration value="CA052"/>
 *     &lt;enumeration value="CA053"/>
 *     &lt;enumeration value="CA054"/>
 *     &lt;enumeration value="CA055"/>
 *     &lt;enumeration value="CA056"/>
 *     &lt;enumeration value="CA057"/>
 *     &lt;enumeration value="CA058"/>
 *     &lt;enumeration value="CA059"/>
 *     &lt;enumeration value="CA060"/>
 *     &lt;enumeration value="CA061"/>
 *     &lt;enumeration value="CA062"/>
 *     &lt;enumeration value="CA063"/>
 *     &lt;enumeration value="CA064"/>
 *     &lt;enumeration value="CA065"/>
 *     &lt;enumeration value="CA066"/>
 *     &lt;enumeration value="CA067"/>
 *     &lt;enumeration value="CA068"/>
 *     &lt;enumeration value="CA069"/>
 *     &lt;enumeration value="CA070"/>
 *     &lt;enumeration value="CA071"/>
 *     &lt;enumeration value="CA072"/>
 *     &lt;enumeration value="CA073"/>
 *     &lt;enumeration value="CA074"/>
 *     &lt;enumeration value="CA075"/>
 *     &lt;enumeration value="CA076"/>
 *     &lt;enumeration value="CA077"/>
 *     &lt;enumeration value="CA078"/>
 *     &lt;enumeration value="CA079"/>
 *     &lt;enumeration value="CA080"/>
 *     &lt;enumeration value="CA081"/>
 *     &lt;enumeration value="CA082"/>
 *     &lt;enumeration value="CA083"/>
 *     &lt;enumeration value="CA084"/>
 *     &lt;enumeration value="CA085"/>
 *     &lt;enumeration value="CA086"/>
 *     &lt;enumeration value="CA087"/>
 *     &lt;enumeration value="CA088"/>
 *     &lt;enumeration value="CA089"/>
 *     &lt;enumeration value="CA090"/>
 *     &lt;enumeration value="CA091"/>
 *     &lt;enumeration value="CA092"/>
 *     &lt;enumeration value="CA093"/>
 *     &lt;enumeration value="CA094"/>
 *     &lt;enumeration value="CA095"/>
 *     &lt;enumeration value="CA096"/>
 *     &lt;enumeration value="CA097"/>
 *     &lt;enumeration value="CA098"/>
 *     &lt;enumeration value="CA099"/>
 *     &lt;enumeration value="CA100"/>
 *     &lt;enumeration value="CA101"/>
 *     &lt;enumeration value="CA102"/>
 *     &lt;enumeration value="CA103"/>
 *     &lt;enumeration value="CA104"/>
 *     &lt;enumeration value="CA105"/>
 *     &lt;enumeration value="CA106"/>
 *     &lt;enumeration value="CA107"/>
 *     &lt;enumeration value="CA108"/>
 *     &lt;enumeration value="CA109"/>
 *     &lt;enumeration value="CA110"/>
 *     &lt;enumeration value="CA111"/>
 *     &lt;enumeration value="CA112"/>
 *     &lt;enumeration value="CA113"/>
 *     &lt;enumeration value="CA114"/>
 *     &lt;enumeration value="CA115"/>
 *     &lt;enumeration value="CA116"/>
 *     &lt;enumeration value="CA117"/>
 *     &lt;enumeration value="CA118"/>
 *     &lt;enumeration value="CA119"/>
 *     &lt;enumeration value="CA120"/>
 *     &lt;enumeration value="CA121"/>
 *     &lt;enumeration value="CA122"/>
 *     &lt;enumeration value="CA123"/>
 *     &lt;enumeration value="CA124"/>
 *     &lt;enumeration value="CA125"/>
 *     &lt;enumeration value="CA126"/>
 *     &lt;enumeration value="CA127"/>
 *     &lt;enumeration value="CA128"/>
 *     &lt;enumeration value="CA129"/>
 *     &lt;enumeration value="CA130"/>
 *     &lt;enumeration value="CA131"/>
 *     &lt;enumeration value="CA132"/>
 *     &lt;enumeration value="CA133"/>
 *     &lt;enumeration value="CA134"/>
 *     &lt;enumeration value="CA135"/>
 *     &lt;enumeration value="CA136"/>
 *     &lt;enumeration value="CA137"/>
 *     &lt;enumeration value="CA138"/>
 *     &lt;enumeration value="CA139"/>
 *     &lt;enumeration value="CA140"/>
 *     &lt;enumeration value="CA141"/>
 *     &lt;enumeration value="CA142"/>
 *     &lt;enumeration value="CA143"/>
 *     &lt;enumeration value="CA144"/>
 *     &lt;enumeration value="CA145"/>
 *     &lt;enumeration value="CA146"/>
 *     &lt;enumeration value="CA147"/>
 *     &lt;enumeration value="CA148"/>
 *     &lt;enumeration value="CA149"/>
 *     &lt;enumeration value="CA150"/>
 *     &lt;enumeration value="CA151"/>
 *     &lt;enumeration value="CA152"/>
 *     &lt;enumeration value="CA153"/>
 *     &lt;enumeration value="CA154"/>
 *     &lt;enumeration value="CA155"/>
 *     &lt;enumeration value="CA156"/>
 *     &lt;enumeration value="CA157"/>
 *     &lt;enumeration value="CA158"/>
 *     &lt;enumeration value="CA159"/>
 *     &lt;enumeration value="CA160"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "c_CodigoTransporteAereo", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte")
@XmlEnum
public enum CCodigoTransporteAereo {

    @XmlEnumValue("CA001")
    CA_001("CA001"),
    @XmlEnumValue("CA002")
    CA_002("CA002"),
    @XmlEnumValue("CA003")
    CA_003("CA003"),
    @XmlEnumValue("CA004")
    CA_004("CA004"),
    @XmlEnumValue("CA005")
    CA_005("CA005"),
    @XmlEnumValue("CA006")
    CA_006("CA006"),
    @XmlEnumValue("CA007")
    CA_007("CA007"),
    @XmlEnumValue("CA008")
    CA_008("CA008"),
    @XmlEnumValue("CA009")
    CA_009("CA009"),
    @XmlEnumValue("CA010")
    CA_010("CA010"),
    @XmlEnumValue("CA011")
    CA_011("CA011"),
    @XmlEnumValue("CA012")
    CA_012("CA012"),
    @XmlEnumValue("CA013")
    CA_013("CA013"),
    @XmlEnumValue("CA014")
    CA_014("CA014"),
    @XmlEnumValue("CA015")
    CA_015("CA015"),
    @XmlEnumValue("CA016")
    CA_016("CA016"),
    @XmlEnumValue("CA017")
    CA_017("CA017"),
    @XmlEnumValue("CA018")
    CA_018("CA018"),
    @XmlEnumValue("CA019")
    CA_019("CA019"),
    @XmlEnumValue("CA020")
    CA_020("CA020"),
    @XmlEnumValue("CA021")
    CA_021("CA021"),
    @XmlEnumValue("CA022")
    CA_022("CA022"),
    @XmlEnumValue("CA023")
    CA_023("CA023"),
    @XmlEnumValue("CA024")
    CA_024("CA024"),
    @XmlEnumValue("CA025")
    CA_025("CA025"),
    @XmlEnumValue("CA026")
    CA_026("CA026"),
    @XmlEnumValue("CA027")
    CA_027("CA027"),
    @XmlEnumValue("CA028")
    CA_028("CA028"),
    @XmlEnumValue("CA029")
    CA_029("CA029"),
    @XmlEnumValue("CA030")
    CA_030("CA030"),
    @XmlEnumValue("CA031")
    CA_031("CA031"),
    @XmlEnumValue("CA032")
    CA_032("CA032"),
    @XmlEnumValue("CA033")
    CA_033("CA033"),
    @XmlEnumValue("CA034")
    CA_034("CA034"),
    @XmlEnumValue("CA035")
    CA_035("CA035"),
    @XmlEnumValue("CA036")
    CA_036("CA036"),
    @XmlEnumValue("CA037")
    CA_037("CA037"),
    @XmlEnumValue("CA038")
    CA_038("CA038"),
    @XmlEnumValue("CA039")
    CA_039("CA039"),
    @XmlEnumValue("CA040")
    CA_040("CA040"),
    @XmlEnumValue("CA041")
    CA_041("CA041"),
    @XmlEnumValue("CA042")
    CA_042("CA042"),
    @XmlEnumValue("CA043")
    CA_043("CA043"),
    @XmlEnumValue("CA044")
    CA_044("CA044"),
    @XmlEnumValue("CA045")
    CA_045("CA045"),
    @XmlEnumValue("CA046")
    CA_046("CA046"),
    @XmlEnumValue("CA047")
    CA_047("CA047"),
    @XmlEnumValue("CA048")
    CA_048("CA048"),
    @XmlEnumValue("CA049")
    CA_049("CA049"),
    @XmlEnumValue("CA050")
    CA_050("CA050"),
    @XmlEnumValue("CA051")
    CA_051("CA051"),
    @XmlEnumValue("CA052")
    CA_052("CA052"),
    @XmlEnumValue("CA053")
    CA_053("CA053"),
    @XmlEnumValue("CA054")
    CA_054("CA054"),
    @XmlEnumValue("CA055")
    CA_055("CA055"),
    @XmlEnumValue("CA056")
    CA_056("CA056"),
    @XmlEnumValue("CA057")
    CA_057("CA057"),
    @XmlEnumValue("CA058")
    CA_058("CA058"),
    @XmlEnumValue("CA059")
    CA_059("CA059"),
    @XmlEnumValue("CA060")
    CA_060("CA060"),
    @XmlEnumValue("CA061")
    CA_061("CA061"),
    @XmlEnumValue("CA062")
    CA_062("CA062"),
    @XmlEnumValue("CA063")
    CA_063("CA063"),
    @XmlEnumValue("CA064")
    CA_064("CA064"),
    @XmlEnumValue("CA065")
    CA_065("CA065"),
    @XmlEnumValue("CA066")
    CA_066("CA066"),
    @XmlEnumValue("CA067")
    CA_067("CA067"),
    @XmlEnumValue("CA068")
    CA_068("CA068"),
    @XmlEnumValue("CA069")
    CA_069("CA069"),
    @XmlEnumValue("CA070")
    CA_070("CA070"),
    @XmlEnumValue("CA071")
    CA_071("CA071"),
    @XmlEnumValue("CA072")
    CA_072("CA072"),
    @XmlEnumValue("CA073")
    CA_073("CA073"),
    @XmlEnumValue("CA074")
    CA_074("CA074"),
    @XmlEnumValue("CA075")
    CA_075("CA075"),
    @XmlEnumValue("CA076")
    CA_076("CA076"),
    @XmlEnumValue("CA077")
    CA_077("CA077"),
    @XmlEnumValue("CA078")
    CA_078("CA078"),
    @XmlEnumValue("CA079")
    CA_079("CA079"),
    @XmlEnumValue("CA080")
    CA_080("CA080"),
    @XmlEnumValue("CA081")
    CA_081("CA081"),
    @XmlEnumValue("CA082")
    CA_082("CA082"),
    @XmlEnumValue("CA083")
    CA_083("CA083"),
    @XmlEnumValue("CA084")
    CA_084("CA084"),
    @XmlEnumValue("CA085")
    CA_085("CA085"),
    @XmlEnumValue("CA086")
    CA_086("CA086"),
    @XmlEnumValue("CA087")
    CA_087("CA087"),
    @XmlEnumValue("CA088")
    CA_088("CA088"),
    @XmlEnumValue("CA089")
    CA_089("CA089"),
    @XmlEnumValue("CA090")
    CA_090("CA090"),
    @XmlEnumValue("CA091")
    CA_091("CA091"),
    @XmlEnumValue("CA092")
    CA_092("CA092"),
    @XmlEnumValue("CA093")
    CA_093("CA093"),
    @XmlEnumValue("CA094")
    CA_094("CA094"),
    @XmlEnumValue("CA095")
    CA_095("CA095"),
    @XmlEnumValue("CA096")
    CA_096("CA096"),
    @XmlEnumValue("CA097")
    CA_097("CA097"),
    @XmlEnumValue("CA098")
    CA_098("CA098"),
    @XmlEnumValue("CA099")
    CA_099("CA099"),
    @XmlEnumValue("CA100")
    CA_100("CA100"),
    @XmlEnumValue("CA101")
    CA_101("CA101"),
    @XmlEnumValue("CA102")
    CA_102("CA102"),
    @XmlEnumValue("CA103")
    CA_103("CA103"),
    @XmlEnumValue("CA104")
    CA_104("CA104"),
    @XmlEnumValue("CA105")
    CA_105("CA105"),
    @XmlEnumValue("CA106")
    CA_106("CA106"),
    @XmlEnumValue("CA107")
    CA_107("CA107"),
    @XmlEnumValue("CA108")
    CA_108("CA108"),
    @XmlEnumValue("CA109")
    CA_109("CA109"),
    @XmlEnumValue("CA110")
    CA_110("CA110"),
    @XmlEnumValue("CA111")
    CA_111("CA111"),
    @XmlEnumValue("CA112")
    CA_112("CA112"),
    @XmlEnumValue("CA113")
    CA_113("CA113"),
    @XmlEnumValue("CA114")
    CA_114("CA114"),
    @XmlEnumValue("CA115")
    CA_115("CA115"),
    @XmlEnumValue("CA116")
    CA_116("CA116"),
    @XmlEnumValue("CA117")
    CA_117("CA117"),
    @XmlEnumValue("CA118")
    CA_118("CA118"),
    @XmlEnumValue("CA119")
    CA_119("CA119"),
    @XmlEnumValue("CA120")
    CA_120("CA120"),
    @XmlEnumValue("CA121")
    CA_121("CA121"),
    @XmlEnumValue("CA122")
    CA_122("CA122"),
    @XmlEnumValue("CA123")
    CA_123("CA123"),
    @XmlEnumValue("CA124")
    CA_124("CA124"),
    @XmlEnumValue("CA125")
    CA_125("CA125"),
    @XmlEnumValue("CA126")
    CA_126("CA126"),
    @XmlEnumValue("CA127")
    CA_127("CA127"),
    @XmlEnumValue("CA128")
    CA_128("CA128"),
    @XmlEnumValue("CA129")
    CA_129("CA129"),
    @XmlEnumValue("CA130")
    CA_130("CA130"),
    @XmlEnumValue("CA131")
    CA_131("CA131"),
    @XmlEnumValue("CA132")
    CA_132("CA132"),
    @XmlEnumValue("CA133")
    CA_133("CA133"),
    @XmlEnumValue("CA134")
    CA_134("CA134"),
    @XmlEnumValue("CA135")
    CA_135("CA135"),
    @XmlEnumValue("CA136")
    CA_136("CA136"),
    @XmlEnumValue("CA137")
    CA_137("CA137"),
    @XmlEnumValue("CA138")
    CA_138("CA138"),
    @XmlEnumValue("CA139")
    CA_139("CA139"),
    @XmlEnumValue("CA140")
    CA_140("CA140"),
    @XmlEnumValue("CA141")
    CA_141("CA141"),
    @XmlEnumValue("CA142")
    CA_142("CA142"),
    @XmlEnumValue("CA143")
    CA_143("CA143"),
    @XmlEnumValue("CA144")
    CA_144("CA144"),
    @XmlEnumValue("CA145")
    CA_145("CA145"),
    @XmlEnumValue("CA146")
    CA_146("CA146"),
    @XmlEnumValue("CA147")
    CA_147("CA147"),
    @XmlEnumValue("CA148")
    CA_148("CA148"),
    @XmlEnumValue("CA149")
    CA_149("CA149"),
    @XmlEnumValue("CA150")
    CA_150("CA150"),
    @XmlEnumValue("CA151")
    CA_151("CA151"),
    @XmlEnumValue("CA152")
    CA_152("CA152"),
    @XmlEnumValue("CA153")
    CA_153("CA153"),
    @XmlEnumValue("CA154")
    CA_154("CA154"),
    @XmlEnumValue("CA155")
    CA_155("CA155"),
    @XmlEnumValue("CA156")
    CA_156("CA156"),
    @XmlEnumValue("CA157")
    CA_157("CA157"),
    @XmlEnumValue("CA158")
    CA_158("CA158"),
    @XmlEnumValue("CA159")
    CA_159("CA159"),
    @XmlEnumValue("CA160")
    CA_160("CA160");
    private final String value;

    CCodigoTransporteAereo(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CCodigoTransporteAereo fromValue(String v) {
        for (CCodigoTransporteAereo c: CCodigoTransporteAereo.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
