//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.02 at 05:28:47 PM CST 
//


package mx.gob.sat.sitio_internet.cfd.catalogos.cartaporte;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_Contenedor.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_Contenedor">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="TC01"/>
 *     &lt;enumeration value="TC02"/>
 *     &lt;enumeration value="TC03"/>
 *     &lt;enumeration value="TC04"/>
 *     &lt;enumeration value="TC05"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "c_Contenedor", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte")
@XmlEnum
public enum CContenedor {

    @XmlEnumValue("TC01")
    TC_01("TC01"),
    @XmlEnumValue("TC02")
    TC_02("TC02"),
    @XmlEnumValue("TC03")
    TC_03("TC03"),
    @XmlEnumValue("TC04")
    TC_04("TC04"),
    @XmlEnumValue("TC05")
    TC_05("TC05");
    private final String value;

    CContenedor(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CContenedor fromValue(String v) {
        for (CContenedor c: CContenedor.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
