//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.02 at 05:28:47 PM CST 
//


package mx.gob.sat.sitio_internet.cfd.catalogos.cartaporte;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_ConfigMaritima.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_ConfigMaritima">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="B01"/>
 *     &lt;enumeration value="B02"/>
 *     &lt;enumeration value="B03"/>
 *     &lt;enumeration value="B04"/>
 *     &lt;enumeration value="B05"/>
 *     &lt;enumeration value="B06"/>
 *     &lt;enumeration value="B07"/>
 *     &lt;enumeration value="B08"/>
 *     &lt;enumeration value="B09"/>
 *     &lt;enumeration value="B10"/>
 *     &lt;enumeration value="B11"/>
 *     &lt;enumeration value="B12"/>
 *     &lt;enumeration value="B13"/>
 *     &lt;enumeration value="B14"/>
 *     &lt;enumeration value="B15"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "c_ConfigMaritima", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte")
@XmlEnum
public enum CConfigMaritima {

    @XmlEnumValue("B01")
    B_01("B01"),
    @XmlEnumValue("B02")
    B_02("B02"),
    @XmlEnumValue("B03")
    B_03("B03"),
    @XmlEnumValue("B04")
    B_04("B04"),
    @XmlEnumValue("B05")
    B_05("B05"),
    @XmlEnumValue("B06")
    B_06("B06"),
    @XmlEnumValue("B07")
    B_07("B07"),
    @XmlEnumValue("B08")
    B_08("B08"),
    @XmlEnumValue("B09")
    B_09("B09"),
    @XmlEnumValue("B10")
    B_10("B10"),
    @XmlEnumValue("B11")
    B_11("B11"),
    @XmlEnumValue("B12")
    B_12("B12"),
    @XmlEnumValue("B13")
    B_13("B13"),
    @XmlEnumValue("B14")
    B_14("B14"),
    @XmlEnumValue("B15")
    B_15("B15");
    private final String value;

    CConfigMaritima(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CConfigMaritima fromValue(String v) {
        for (CConfigMaritima c: CConfigMaritima.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
