//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 01:43:49 PM CDT 
//


package mx.gob.sat.sitio_internet.cfd.catalogos.cartaporte;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_Contenedor.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_Contenedor"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;whiteSpace value="collapse"/&gt;
 *     &lt;enumeration value="TC01"/&gt;
 *     &lt;enumeration value="TC02"/&gt;
 *     &lt;enumeration value="TC03"/&gt;
 *     &lt;enumeration value="TC04"/&gt;
 *     &lt;enumeration value="TC05"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "c_Contenedor", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte")
@XmlEnum
public enum CContenedor {

    @XmlEnumValue("TC01")
    TC_01("TC01"),
    @XmlEnumValue("TC02")
    TC_02("TC02"),
    @XmlEnumValue("TC03")
    TC_03("TC03"),
    @XmlEnumValue("TC04")
    TC_04("TC04"),
    @XmlEnumValue("TC05")
    TC_05("TC05");
    private final String value;

    CContenedor(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CContenedor fromValue(String v) {
        for (CContenedor c: CContenedor.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
