//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.02 at 05:28:47 PM CST 
//


package mx.gob.sat.sitio_internet.cfd.catalogos.cartaporte;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_DerechosDePaso.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_DerechosDePaso">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="CDP001"/>
 *     &lt;enumeration value="CDP002"/>
 *     &lt;enumeration value="CDP003"/>
 *     &lt;enumeration value="CDP004"/>
 *     &lt;enumeration value="CDP005"/>
 *     &lt;enumeration value="CDP006"/>
 *     &lt;enumeration value="CDP007"/>
 *     &lt;enumeration value="CDP008"/>
 *     &lt;enumeration value="CDP009"/>
 *     &lt;enumeration value="CDP010"/>
 *     &lt;enumeration value="CDP011"/>
 *     &lt;enumeration value="CDP012"/>
 *     &lt;enumeration value="CDP013"/>
 *     &lt;enumeration value="CDP014"/>
 *     &lt;enumeration value="CDP015"/>
 *     &lt;enumeration value="CDP016"/>
 *     &lt;enumeration value="CDP017"/>
 *     &lt;enumeration value="CDP018"/>
 *     &lt;enumeration value="CDP019"/>
 *     &lt;enumeration value="CDP020"/>
 *     &lt;enumeration value="CDP021"/>
 *     &lt;enumeration value="CDP022"/>
 *     &lt;enumeration value="CDP023"/>
 *     &lt;enumeration value="CDP024"/>
 *     &lt;enumeration value="CDP025"/>
 *     &lt;enumeration value="CDP026"/>
 *     &lt;enumeration value="CDP027"/>
 *     &lt;enumeration value="CDP028"/>
 *     &lt;enumeration value="CDP029"/>
 *     &lt;enumeration value="CDP030"/>
 *     &lt;enumeration value="CDP031"/>
 *     &lt;enumeration value="CDP032"/>
 *     &lt;enumeration value="CDP033"/>
 *     &lt;enumeration value="CDP034"/>
 *     &lt;enumeration value="CDP035"/>
 *     &lt;enumeration value="CDP036"/>
 *     &lt;enumeration value="CDP037"/>
 *     &lt;enumeration value="CDP038"/>
 *     &lt;enumeration value="CDP039"/>
 *     &lt;enumeration value="CDP040"/>
 *     &lt;enumeration value="CDP041"/>
 *     &lt;enumeration value="CDP042"/>
 *     &lt;enumeration value="CDP043"/>
 *     &lt;enumeration value="CDP044"/>
 *     &lt;enumeration value="CDP045"/>
 *     &lt;enumeration value="CDP046"/>
 *     &lt;enumeration value="CDP047"/>
 *     &lt;enumeration value="CDP048"/>
 *     &lt;enumeration value="CDP049"/>
 *     &lt;enumeration value="CDP050"/>
 *     &lt;enumeration value="CDP051"/>
 *     &lt;enumeration value="CDP052"/>
 *     &lt;enumeration value="CDP053"/>
 *     &lt;enumeration value="CDP054"/>
 *     &lt;enumeration value="CDP055"/>
 *     &lt;enumeration value="CDP056"/>
 *     &lt;enumeration value="CDP057"/>
 *     &lt;enumeration value="CDP058"/>
 *     &lt;enumeration value="CDP059"/>
 *     &lt;enumeration value="CDP060"/>
 *     &lt;enumeration value="CDP061"/>
 *     &lt;enumeration value="CDP062"/>
 *     &lt;enumeration value="CDP063"/>
 *     &lt;enumeration value="CDP064"/>
 *     &lt;enumeration value="CDP065"/>
 *     &lt;enumeration value="CDP066"/>
 *     &lt;enumeration value="CDP067"/>
 *     &lt;enumeration value="CDP068"/>
 *     &lt;enumeration value="CDP069"/>
 *     &lt;enumeration value="CDP070"/>
 *     &lt;enumeration value="CDP071"/>
 *     &lt;enumeration value="CDP072"/>
 *     &lt;enumeration value="CDP073"/>
 *     &lt;enumeration value="CDP074"/>
 *     &lt;enumeration value="CDP075"/>
 *     &lt;enumeration value="CDP076"/>
 *     &lt;enumeration value="CDP077"/>
 *     &lt;enumeration value="CDP078"/>
 *     &lt;enumeration value="CDP079"/>
 *     &lt;enumeration value="CDP080"/>
 *     &lt;enumeration value="CDP081"/>
 *     &lt;enumeration value="CDP082"/>
 *     &lt;enumeration value="CDP083"/>
 *     &lt;enumeration value="CDP084"/>
 *     &lt;enumeration value="CDP085"/>
 *     &lt;enumeration value="CDP086"/>
 *     &lt;enumeration value="CDP087"/>
 *     &lt;enumeration value="CDP088"/>
 *     &lt;enumeration value="CDP089"/>
 *     &lt;enumeration value="CDP090"/>
 *     &lt;enumeration value="CDP091"/>
 *     &lt;enumeration value="CDP092"/>
 *     &lt;enumeration value="CDP093"/>
 *     &lt;enumeration value="CDP094"/>
 *     &lt;enumeration value="CDP095"/>
 *     &lt;enumeration value="CDP096"/>
 *     &lt;enumeration value="CDP097"/>
 *     &lt;enumeration value="CDP098"/>
 *     &lt;enumeration value="CDP099"/>
 *     &lt;enumeration value="CDP100"/>
 *     &lt;enumeration value="CDP101"/>
 *     &lt;enumeration value="CDP102"/>
 *     &lt;enumeration value="CDP103"/>
 *     &lt;enumeration value="CDP104"/>
 *     &lt;enumeration value="CDP105"/>
 *     &lt;enumeration value="CDP106"/>
 *     &lt;enumeration value="CDP107"/>
 *     &lt;enumeration value="CDP108"/>
 *     &lt;enumeration value="CDP109"/>
 *     &lt;enumeration value="CDP110"/>
 *     &lt;enumeration value="CDP111"/>
 *     &lt;enumeration value="CDP112"/>
 *     &lt;enumeration value="CDP113"/>
 *     &lt;enumeration value="CDP114"/>
 *     &lt;enumeration value="CDP115"/>
 *     &lt;enumeration value="CDP116"/>
 *     &lt;enumeration value="CDP117"/>
 *     &lt;enumeration value="CDP118"/>
 *     &lt;enumeration value="CDP119"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "c_DerechosDePaso", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte")
@XmlEnum
public enum CDerechosDePaso {

    @XmlEnumValue("CDP001")
    CDP_001("CDP001"),
    @XmlEnumValue("CDP002")
    CDP_002("CDP002"),
    @XmlEnumValue("CDP003")
    CDP_003("CDP003"),
    @XmlEnumValue("CDP004")
    CDP_004("CDP004"),
    @XmlEnumValue("CDP005")
    CDP_005("CDP005"),
    @XmlEnumValue("CDP006")
    CDP_006("CDP006"),
    @XmlEnumValue("CDP007")
    CDP_007("CDP007"),
    @XmlEnumValue("CDP008")
    CDP_008("CDP008"),
    @XmlEnumValue("CDP009")
    CDP_009("CDP009"),
    @XmlEnumValue("CDP010")
    CDP_010("CDP010"),
    @XmlEnumValue("CDP011")
    CDP_011("CDP011"),
    @XmlEnumValue("CDP012")
    CDP_012("CDP012"),
    @XmlEnumValue("CDP013")
    CDP_013("CDP013"),
    @XmlEnumValue("CDP014")
    CDP_014("CDP014"),
    @XmlEnumValue("CDP015")
    CDP_015("CDP015"),
    @XmlEnumValue("CDP016")
    CDP_016("CDP016"),
    @XmlEnumValue("CDP017")
    CDP_017("CDP017"),
    @XmlEnumValue("CDP018")
    CDP_018("CDP018"),
    @XmlEnumValue("CDP019")
    CDP_019("CDP019"),
    @XmlEnumValue("CDP020")
    CDP_020("CDP020"),
    @XmlEnumValue("CDP021")
    CDP_021("CDP021"),
    @XmlEnumValue("CDP022")
    CDP_022("CDP022"),
    @XmlEnumValue("CDP023")
    CDP_023("CDP023"),
    @XmlEnumValue("CDP024")
    CDP_024("CDP024"),
    @XmlEnumValue("CDP025")
    CDP_025("CDP025"),
    @XmlEnumValue("CDP026")
    CDP_026("CDP026"),
    @XmlEnumValue("CDP027")
    CDP_027("CDP027"),
    @XmlEnumValue("CDP028")
    CDP_028("CDP028"),
    @XmlEnumValue("CDP029")
    CDP_029("CDP029"),
    @XmlEnumValue("CDP030")
    CDP_030("CDP030"),
    @XmlEnumValue("CDP031")
    CDP_031("CDP031"),
    @XmlEnumValue("CDP032")
    CDP_032("CDP032"),
    @XmlEnumValue("CDP033")
    CDP_033("CDP033"),
    @XmlEnumValue("CDP034")
    CDP_034("CDP034"),
    @XmlEnumValue("CDP035")
    CDP_035("CDP035"),
    @XmlEnumValue("CDP036")
    CDP_036("CDP036"),
    @XmlEnumValue("CDP037")
    CDP_037("CDP037"),
    @XmlEnumValue("CDP038")
    CDP_038("CDP038"),
    @XmlEnumValue("CDP039")
    CDP_039("CDP039"),
    @XmlEnumValue("CDP040")
    CDP_040("CDP040"),
    @XmlEnumValue("CDP041")
    CDP_041("CDP041"),
    @XmlEnumValue("CDP042")
    CDP_042("CDP042"),
    @XmlEnumValue("CDP043")
    CDP_043("CDP043"),
    @XmlEnumValue("CDP044")
    CDP_044("CDP044"),
    @XmlEnumValue("CDP045")
    CDP_045("CDP045"),
    @XmlEnumValue("CDP046")
    CDP_046("CDP046"),
    @XmlEnumValue("CDP047")
    CDP_047("CDP047"),
    @XmlEnumValue("CDP048")
    CDP_048("CDP048"),
    @XmlEnumValue("CDP049")
    CDP_049("CDP049"),
    @XmlEnumValue("CDP050")
    CDP_050("CDP050"),
    @XmlEnumValue("CDP051")
    CDP_051("CDP051"),
    @XmlEnumValue("CDP052")
    CDP_052("CDP052"),
    @XmlEnumValue("CDP053")
    CDP_053("CDP053"),
    @XmlEnumValue("CDP054")
    CDP_054("CDP054"),
    @XmlEnumValue("CDP055")
    CDP_055("CDP055"),
    @XmlEnumValue("CDP056")
    CDP_056("CDP056"),
    @XmlEnumValue("CDP057")
    CDP_057("CDP057"),
    @XmlEnumValue("CDP058")
    CDP_058("CDP058"),
    @XmlEnumValue("CDP059")
    CDP_059("CDP059"),
    @XmlEnumValue("CDP060")
    CDP_060("CDP060"),
    @XmlEnumValue("CDP061")
    CDP_061("CDP061"),
    @XmlEnumValue("CDP062")
    CDP_062("CDP062"),
    @XmlEnumValue("CDP063")
    CDP_063("CDP063"),
    @XmlEnumValue("CDP064")
    CDP_064("CDP064"),
    @XmlEnumValue("CDP065")
    CDP_065("CDP065"),
    @XmlEnumValue("CDP066")
    CDP_066("CDP066"),
    @XmlEnumValue("CDP067")
    CDP_067("CDP067"),
    @XmlEnumValue("CDP068")
    CDP_068("CDP068"),
    @XmlEnumValue("CDP069")
    CDP_069("CDP069"),
    @XmlEnumValue("CDP070")
    CDP_070("CDP070"),
    @XmlEnumValue("CDP071")
    CDP_071("CDP071"),
    @XmlEnumValue("CDP072")
    CDP_072("CDP072"),
    @XmlEnumValue("CDP073")
    CDP_073("CDP073"),
    @XmlEnumValue("CDP074")
    CDP_074("CDP074"),
    @XmlEnumValue("CDP075")
    CDP_075("CDP075"),
    @XmlEnumValue("CDP076")
    CDP_076("CDP076"),
    @XmlEnumValue("CDP077")
    CDP_077("CDP077"),
    @XmlEnumValue("CDP078")
    CDP_078("CDP078"),
    @XmlEnumValue("CDP079")
    CDP_079("CDP079"),
    @XmlEnumValue("CDP080")
    CDP_080("CDP080"),
    @XmlEnumValue("CDP081")
    CDP_081("CDP081"),
    @XmlEnumValue("CDP082")
    CDP_082("CDP082"),
    @XmlEnumValue("CDP083")
    CDP_083("CDP083"),
    @XmlEnumValue("CDP084")
    CDP_084("CDP084"),
    @XmlEnumValue("CDP085")
    CDP_085("CDP085"),
    @XmlEnumValue("CDP086")
    CDP_086("CDP086"),
    @XmlEnumValue("CDP087")
    CDP_087("CDP087"),
    @XmlEnumValue("CDP088")
    CDP_088("CDP088"),
    @XmlEnumValue("CDP089")
    CDP_089("CDP089"),
    @XmlEnumValue("CDP090")
    CDP_090("CDP090"),
    @XmlEnumValue("CDP091")
    CDP_091("CDP091"),
    @XmlEnumValue("CDP092")
    CDP_092("CDP092"),
    @XmlEnumValue("CDP093")
    CDP_093("CDP093"),
    @XmlEnumValue("CDP094")
    CDP_094("CDP094"),
    @XmlEnumValue("CDP095")
    CDP_095("CDP095"),
    @XmlEnumValue("CDP096")
    CDP_096("CDP096"),
    @XmlEnumValue("CDP097")
    CDP_097("CDP097"),
    @XmlEnumValue("CDP098")
    CDP_098("CDP098"),
    @XmlEnumValue("CDP099")
    CDP_099("CDP099"),
    @XmlEnumValue("CDP100")
    CDP_100("CDP100"),
    @XmlEnumValue("CDP101")
    CDP_101("CDP101"),
    @XmlEnumValue("CDP102")
    CDP_102("CDP102"),
    @XmlEnumValue("CDP103")
    CDP_103("CDP103"),
    @XmlEnumValue("CDP104")
    CDP_104("CDP104"),
    @XmlEnumValue("CDP105")
    CDP_105("CDP105"),
    @XmlEnumValue("CDP106")
    CDP_106("CDP106"),
    @XmlEnumValue("CDP107")
    CDP_107("CDP107"),
    @XmlEnumValue("CDP108")
    CDP_108("CDP108"),
    @XmlEnumValue("CDP109")
    CDP_109("CDP109"),
    @XmlEnumValue("CDP110")
    CDP_110("CDP110"),
    @XmlEnumValue("CDP111")
    CDP_111("CDP111"),
    @XmlEnumValue("CDP112")
    CDP_112("CDP112"),
    @XmlEnumValue("CDP113")
    CDP_113("CDP113"),
    @XmlEnumValue("CDP114")
    CDP_114("CDP114"),
    @XmlEnumValue("CDP115")
    CDP_115("CDP115"),
    @XmlEnumValue("CDP116")
    CDP_116("CDP116"),
    @XmlEnumValue("CDP117")
    CDP_117("CDP117"),
    @XmlEnumValue("CDP118")
    CDP_118("CDP118"),
    @XmlEnumValue("CDP119")
    CDP_119("CDP119");
    private final String value;

    CDerechosDePaso(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CDerechosDePaso fromValue(String v) {
        for (CDerechosDePaso c: CDerechosDePaso.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
