//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.02 at 05:28:47 PM CST 
//


package mx.gob.sat.sitio_internet.cfd.catalogos.cartaporte;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_ParteTransporte.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_ParteTransporte">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="PT01"/>
 *     &lt;enumeration value="PT02"/>
 *     &lt;enumeration value="PT03"/>
 *     &lt;enumeration value="PT04"/>
 *     &lt;enumeration value="PT05"/>
 *     &lt;enumeration value="PT06"/>
 *     &lt;enumeration value="PT07"/>
 *     &lt;enumeration value="PT08"/>
 *     &lt;enumeration value="PT09"/>
 *     &lt;enumeration value="PT10"/>
 *     &lt;enumeration value="PT11"/>
 *     &lt;enumeration value="PT12"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "c_ParteTransporte", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte")
@XmlEnum
public enum CParteTransporte {

    @XmlEnumValue("PT01")
    PT_01("PT01"),
    @XmlEnumValue("PT02")
    PT_02("PT02"),
    @XmlEnumValue("PT03")
    PT_03("PT03"),
    @XmlEnumValue("PT04")
    PT_04("PT04"),
    @XmlEnumValue("PT05")
    PT_05("PT05"),
    @XmlEnumValue("PT06")
    PT_06("PT06"),
    @XmlEnumValue("PT07")
    PT_07("PT07"),
    @XmlEnumValue("PT08")
    PT_08("PT08"),
    @XmlEnumValue("PT09")
    PT_09("PT09"),
    @XmlEnumValue("PT10")
    PT_10("PT10"),
    @XmlEnumValue("PT11")
    PT_11("PT11"),
    @XmlEnumValue("PT12")
    PT_12("PT12");
    private final String value;

    CParteTransporte(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CParteTransporte fromValue(String v) {
        for (CParteTransporte c: CParteTransporte.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
