//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.02 at 05:28:47 PM CST 
//


package mx.gob.sat.sitio_internet.cfd.catalogos.cartaporte;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_TipoPermiso.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_TipoPermiso">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="TPAF01"/>
 *     &lt;enumeration value="TPAF02"/>
 *     &lt;enumeration value="TPAF03"/>
 *     &lt;enumeration value="TPAF04"/>
 *     &lt;enumeration value="TPAF05"/>
 *     &lt;enumeration value="TPAF06"/>
 *     &lt;enumeration value="TPAF07"/>
 *     &lt;enumeration value="TPAF08"/>
 *     &lt;enumeration value="TPAF09"/>
 *     &lt;enumeration value="TPAF10"/>
 *     &lt;enumeration value="TPAF11"/>
 *     &lt;enumeration value="TPAF12"/>
 *     &lt;enumeration value="TPAF13"/>
 *     &lt;enumeration value="TPAF14"/>
 *     &lt;enumeration value="TPAF15"/>
 *     &lt;enumeration value="TPAF16"/>
 *     &lt;enumeration value="TPAF17"/>
 *     &lt;enumeration value="TPAF18"/>
 *     &lt;enumeration value="TPAF19"/>
 *     &lt;enumeration value="TPAF20"/>
 *     &lt;enumeration value="TPTM01"/>
 *     &lt;enumeration value="TPTA01"/>
 *     &lt;enumeration value="TPTA02"/>
 *     &lt;enumeration value="TPTA03"/>
 *     &lt;enumeration value="TPTA04"/>
 *     &lt;enumeration value="TPXX00"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "c_TipoPermiso", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte")
@XmlEnum
public enum CTipoPermiso {

    @XmlEnumValue("TPAF01")
    TPAF_01("TPAF01"),
    @XmlEnumValue("TPAF02")
    TPAF_02("TPAF02"),
    @XmlEnumValue("TPAF03")
    TPAF_03("TPAF03"),
    @XmlEnumValue("TPAF04")
    TPAF_04("TPAF04"),
    @XmlEnumValue("TPAF05")
    TPAF_05("TPAF05"),
    @XmlEnumValue("TPAF06")
    TPAF_06("TPAF06"),
    @XmlEnumValue("TPAF07")
    TPAF_07("TPAF07"),
    @XmlEnumValue("TPAF08")
    TPAF_08("TPAF08"),
    @XmlEnumValue("TPAF09")
    TPAF_09("TPAF09"),
    @XmlEnumValue("TPAF10")
    TPAF_10("TPAF10"),
    @XmlEnumValue("TPAF11")
    TPAF_11("TPAF11"),
    @XmlEnumValue("TPAF12")
    TPAF_12("TPAF12"),
    @XmlEnumValue("TPAF13")
    TPAF_13("TPAF13"),
    @XmlEnumValue("TPAF14")
    TPAF_14("TPAF14"),
    @XmlEnumValue("TPAF15")
    TPAF_15("TPAF15"),
    @XmlEnumValue("TPAF16")
    TPAF_16("TPAF16"),
    @XmlEnumValue("TPAF17")
    TPAF_17("TPAF17"),
    @XmlEnumValue("TPAF18")
    TPAF_18("TPAF18"),
    @XmlEnumValue("TPAF19")
    TPAF_19("TPAF19"),
    @XmlEnumValue("TPAF20")
    TPAF_20("TPAF20"),
    @XmlEnumValue("TPTM01")
    TPTM_01("TPTM01"),
    @XmlEnumValue("TPTA01")
    TPTA_01("TPTA01"),
    @XmlEnumValue("TPTA02")
    TPTA_02("TPTA02"),
    @XmlEnumValue("TPTA03")
    TPTA_03("TPTA03"),
    @XmlEnumValue("TPTA04")
    TPTA_04("TPTA04"),
    @XmlEnumValue("TPXX00")
    TPXX_00("TPXX00");
    private final String value;

    CTipoPermiso(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CTipoPermiso fromValue(String v) {
        for (CTipoPermiso c: CTipoPermiso.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
