//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.02 at 05:28:47 PM CST 
//


package mx.gob.sat.sitio_internet.cfd.catalogos.cartaporte;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_TipoDeServicio.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_TipoDeServicio">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="TS01"/>
 *     &lt;enumeration value="TS02"/>
 *     &lt;enumeration value="TS03"/>
 *     &lt;enumeration value="TS04"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "c_TipoDeServicio", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos/CartaPorte")
@XmlEnum
public enum CTipoDeServicio {

    @XmlEnumValue("TS01")
    TS_01("TS01"),
    @XmlEnumValue("TS02")
    TS_02("TS02"),
    @XmlEnumValue("TS03")
    TS_03("TS03"),
    @XmlEnumValue("TS04")
    TS_04("TS04");
    private final String value;

    CTipoDeServicio(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CTipoDeServicio fromValue(String v) {
        for (CTipoDeServicio c: CTipoDeServicio.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
