apiVersion: v1
kind: Service
metadata:
  labels:
    app: cfdi-srv
    project: as400-extension
  name: cfdi-srv
  namespace: trailera
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    app: cfdi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cfdi-dpl
    project: as400-extension
  namespace: trailera
  name: cfdi-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cfdi
  template:
    metadata:
      labels:
        app: cfdi
        project: as400-extension
    spec:
      volumes:
      - name: pem
        hostPath:
          path: "/DISK/DOS/keys"
          type: Directory
      - name: resources
        hostPath:
          path: "/DISK/DOS/resources/a"
          type: Directory
      containers:
      - image: localhost:5000/lola/cfdi:latest
        name: cfdi
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: redis-srv
        - name: REDIS_PORT
          value: "6379"
        - name: BUCKET_REGION
          valueFrom:
            configMapKeyRef:
              name: lola-out-a-cmap
              key: region
        - name: BUCKET_TARGET
          valueFrom:
            configMapKeyRef:
              name: lola-out-a-cmap
              key: target
        - name: BUCKET_KEY
          valueFrom:
            secretKeyRef:
              name: lola-out-sec
              key: aws_access_key_id
        - name: BUCKET_SECRET
          valueFrom:
            secretKeyRef:
              name: lola-out-sec
              key: aws_secret_access_key
        volumeMounts:
        - mountPath: /pem
          name: pem
        - mountPath: /resources
          name: resources
