apiVersion: v1
kind: Service
metadata:
  labels:
    app: cfdi-srv
    project: as400-extension
  name: cfdi-srv
  namespace: trailera
spec:
  type: NodePort
  ports:
  - port: 4567
    protocol: TCP
    targetPort: 4567
    nodePort: 30567
  selector:
    app: cfdi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cfdi-dpl
    project: as400-extension
  namespace: trailera
  name: cfdi-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cfdi
  template:
    metadata:
      labels:
        app: cfdi
        project: as400-extension
    spec:
      containers:
      - image: localhost:5000/lola/cfdi:latest
        name: cfdi
        imagePullPolicy: Always
        ports:
        - containerPort: 4567
        env:
        - name: REDIS_HOST
          value: redis-srv
        - name: REDIS_PORT
          value: "6379"
