apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tq-rproxy
  namespace: trailera
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: sso.tq.uki
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sso-srv
                port:
                  number: 10100
