apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tq-rproxy
  namespace: trailera
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: lola-cfdi-a.tq.com.mx
      http:
        paths:
          - path: /api/auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: sso-srv
                port:
                  number: 10100
          - path: /api/issue(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: cfdi-srv
                port:
                  number: 8080
    - host: lola-cfdi-b.tq.com.mx
      http:
        paths:
          - path: /api/auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: sso-srv
                port:
                  number: 10100
          - path: /api/issue(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: cfdi-b-srv
                port:
                  number: 8090
