apiVersion: v1
kind: Service
metadata:
  labels:
    app: sso-srv
    project: as400-extension
  name: sso-srv
  namespace: trailera
spec:
  ports:
  - port: 10100
    protocol: TCP
    targetPort: 10100
  selector:
    app: sso

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sso-dpl
    project: as400-extension
  namespace: trailera
  name: sso-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sso
  template:
    metadata:
      labels:
        app: sso
        project: as400-extension
    spec:
      volumes:
      - name: acl
        hostPath:
          path: "/DISK/DOS/acl"
          type: Directory
      - name: pem
        hostPath:
          path: "/DISK/DOS/keys"
          type: Directory
      containers:
      - image: localhost:5000/lola/sso:latest
        name: sso
        imagePullPolicy: Always
        ports:
        - containerPort: 10100
        volumeMounts:
        - mountPath: /acl
          name: acl
        - mountPath: /pem
          name: pem
